server:
  port: 8081
  servlet:
    context-path: /job-test

spring:
  application:
    name: job-test

zookeeper:
  server: 127.0.0.1:2181
  sessionTimeoutMs: 6000
  connectionTimeoutMs: 6000
  maxRetries: 3
  baseSleepTimeMs: 1000
  group: job
  nodeName: UserJob